export const WEBSITE_NAME_KEY = "WEBSITE_NAME";
export const WEBSITE_URL_KEY = "WEBSITE_URL";
export const ADMIN_NAME_KEY = "ADMIN_NAME";
export const AUTHOR_URL_KEY = "AUTHOR_URL";
export const ABOUT_KEY = "ABOUT";
export const DONATION_KEY = "DONATION";
export const WEBSITE_DESCRIPTION_KEY = "WEBSITE_DESCRIPTION";
export const WEBSITE_KEYWORDS_KEY = "WEBSITE_KEYWORDS";

export const ADMIN_EMAIL_KEY = "ADMIN_EMAIL";

export const MAKE_FRIEND_DESCRIPTION_KEY = "MAKE_FRIEND_DESCRIPTION";
