export const WEBSITE_NAME_KEY = "WEBSITE_NAME";
export const ADMIN_NAME_KEY = "ADMIN_NAME";
export const ABOUT_KEY = "ABOUT";
export const WEBSITE_DESCRIPTION_KEY = "WEBSITE_DESCRIPTION";
export const WEBSITE_KEYWORDS_KEY = "WEBSITE_KEYWORDS";

export const ADMIN_EMAIL_KEY = "ADMIN_EMAIL_KEY";
