version: "3.3"

services:
  sprout:
    ports:
      - 3000:3000
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./:/opt/sprout
      - /opt/sprout/node_modules
      - /opt/sprout/.next
networks:
  default:
    external:
      name: mybridge
