name: Build & Publish

on:
  push:
    branches:
      - "master"
      - "!dependabot/**"      # exclude dependabot branches

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: copy file via ssh key
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ALIYUN_SECRET_KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.ALIYUN_HOST }}
          REMOTE_USER: ${{ secrets.ALIYUN_USER }}
          TARGET: "/opt/sprout"
          EXCLUDE: "/dist/, /node_modules/"
      - name: run with docker-compose
        run: "ssh ${{ secrets.ALIYUN_USER }}@${{ secrets.ALIYUN_HOST}} 'cd /opt/sprout && docker-compose up -d'"